name: Release

on: push

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Golang version
        uses: actions/setup-go@v5
        with:
          go-version: '^1.22'
          check-latest: true

      - name: check version
        run: |
          go version

      - name: Build
        run: make build

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            bin/json-helper.darwin.arm64
            bin/json-helper.darwin.x86_64
            bin/json-helper.linux.aarch64
            bin/json-helper.linux.x86_64
            bin/json-helper.x86_64.exe
