name: Self service for the info.json file

on:
  push:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: update info.json
        env:
          RELEVANT_SHA: ${{ github.event.pull_request.head.sha || github.sha }}
        run: |
          curl -sL --create-dirs https://github.com/go-shortcut/json-bumper/releases/download/0.0.1/json-helper.linux.x86_64 -o ~/.local/bin/json-helper
          chmod +x "${_}"
          json-helper info.json bump patch  version
          json-helper info.json bump int    build_id
          json-helper info.json bump date   date
          # not implemented yet
          # json-helper info.json set  string commit ${RELEVANT_SHA:0:7}
          cat info.json

      - name: commit changes
        run: |
          git config --global user.name  "${{ github.event.pusher.name }}"
          git config --global user.email "${{ github.event.pusher.email }}"
          git add info.json
          git commit -m "auto-bump info.json"
          git push
